name: tests

on: [push]

jobs:
  test_in_UW_Container:
    runs-on: ubuntu-latest
    container:
      image: underworldcode/underworld2:2.9.4b
      options: --user root
    steps:
      - name: Test in UW Container
        run: |
          cd /home/jovyan/workspace
          git clone https://github.com/underworldcode/UWGeodynamics.git UWGeodynamics
          cd UWGeodynamics
          git checkout development
          pip install -e .
          pip install pytest
          python -m pytest -vvv